/* ROLES MAS VISTAS ASIGNADAS */
CREATE ROLE luisflahan WITH LOGIN 
	SUPERUSER 
	CREATEDB 
	CREATEROLE 
	INHERIT 
	REPLICATION 
	CONNECTION LIMIT -1 
	PASSWORD '4051'
;


CREATE USER simpleUser PASSWORD '123';
ALTER ROLE simpleUser WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
;


CREATE USER simpleUserWithoutPriv PASSWORD '123';
ALTER ROLE simpleUserWithoutPriv WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
;