// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Details   *string `json:"details"`
	Category  *string `json:"category"`
	Stock     *int    `json:"stock"`
	Exists    *bool   `json:"exists"`
	Scare     *bool   `json:"scare"`
	IDBranch  *int    `json:"id_branch"`
	IDControl *int    `json:"id_control"`
}

type ArticleByID struct {
	ID string `json:"id"`
}

type Branch struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Adress           *string `json:"adress"`
	CopiesBlackWhite *int    `json:"copiesBlackWhite"`
	CopiesColor      *int    `json:"copiesColor"`
	PrintsBlackWhite *int    `json:"printsBlackWhite"`
	PrintsColor      *int    `json:"printsColor"`
	Cash             *int    `json:"cash"`
}

type BranchByID struct {
	ID string `json:"id"`
}

type ControlUser struct {
	ID                string   `json:"id"`
	CheckInDate       string   `json:"checkInDate"`
	CheckOutDate      string   `json:"checkOutDate"`
	CheckInTime       string   `json:"checkInTime"`
	CheckOutTime      string   `json:"checkOutTime"`
	CopiesBlackWhite  *int     `json:"copiesBlackWhite"`
	CopiesColor       *int     `json:"copiesColor"`
	PrintsBlackWhite  *int     `json:"printsBlackWhite"`
	PrintsColor       *int     `json:"printsColor"`
	InitialCash       *float64 `json:"initialCash"`
	Pennies50         *int     `json:"pennies50"`
	Coins1            *int     `json:"coins1"`
	Coins2            *int     `json:"coins2"`
	Coins5            *int     `json:"coins5"`
	Coins10           *int     `json:"coins10"`
	Coins20           *int     `json:"coins20"`
	Bills20           *int     `json:"bills20"`
	Bills50           *int     `json:"bills50"`
	Bills100          *int     `json:"bills100"`
	Bills200          *int     `json:"bills200"`
	Bills500          *int     `json:"bills500"`
	Bills1000         *int     `json:"bills1000"`
	IDResponsibleUser *int     `json:"id_responsibleUser"`
	IDReceiveUser     *int     `json:"id_receiveUser"`
}

type ControlUserByID struct {
	ID string `json:"id"`
}

type NewArticle struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Details   *string `json:"details"`
	Category  *string `json:"category"`
	Stock     *int    `json:"stock"`
	Exists    *bool   `json:"exists"`
	Scare     *bool   `json:"scare"`
	IDBranch  *int    `json:"id_branch"`
	IDControl *int    `json:"id_control"`
}

type NewBranch struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Adress           *string `json:"adress"`
	CopiesBlackWhite *int    `json:"copiesBlackWhite"`
	CopiesColor      *int    `json:"copiesColor"`
	PrintsBlackWhite *int    `json:"printsBlackWhite"`
	PrintsColor      *int    `json:"printsColor"`
	Cash             *int    `json:"cash"`
}

type NewControlUser struct {
	ID                string   `json:"id"`
	CheckInDate       string   `json:"checkInDate"`
	CheckOutDate      string   `json:"checkOutDate"`
	CheckInTime       string   `json:"checkInTime"`
	CheckOutTime      string   `json:"checkOutTime"`
	CopiesBlackWhite  *int     `json:"copiesBlackWhite"`
	CopiesColor       *int     `json:"copiesColor"`
	PrintsBlackWhite  *int     `json:"printsBlackWhite"`
	PrintsColor       *int     `json:"printsColor"`
	InitialCash       *float64 `json:"initialCash"`
	Pennies50         *int     `json:"pennies50"`
	Coins1            *int     `json:"coins1"`
	Coins2            *int     `json:"coins2"`
	Coins5            *int     `json:"coins5"`
	Coins10           *int     `json:"coins10"`
	Coins20           *int     `json:"coins20"`
	Bills20           *int     `json:"bills20"`
	Bills50           *int     `json:"bills50"`
	Bills100          *int     `json:"bills100"`
	Bills200          *int     `json:"bills200"`
	Bills500          *int     `json:"bills500"`
	Bills1000         *int     `json:"bills1000"`
	IDResponsibleUser *int     `json:"id_responsibleUser"`
	IDReceiveUser     *int     `json:"id_receiveUser"`
}

type NewObservations struct {
	ID       string   `json:"id"`
	Details  *string  `json:"details"`
	Income   *float64 `json:"income"`
	Expenses *float64 `json:"expenses"`
}

type NewProduct struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Details   *string  `json:"details"`
	BasePrice *float64 `json:"basePrice"`
	Stock     *int     `json:"stock"`
	Sale      *int     `json:"sale"`
	IDBranch  *int     `json:"id_branch"`
	IDControl *int     `json:"id_control"`
}

type NewUser struct {
	ID               string  `json:"id"`
	Name             *string `json:"name"`
	LastName         *string `json:"lastName"`
	Nickname         string  `json:"nickname"`
	Mail             *string `json:"mail"`
	Phone            *string `json:"phone"`
	Password         string  `json:"password"`
	Admin            *bool   `json:"admin"`
	Root             *bool   `json:"root"`
	RegistrationDate *string `json:"registrationDate"`
	IDBranch         *int    `json:"id_branch"`
}

type Observations struct {
	ID       string   `json:"id"`
	Details  *string  `json:"details"`
	Income   *float64 `json:"income"`
	Expenses *float64 `json:"expenses"`
}

type ObservationsByID struct {
	ID string `json:"id"`
}

type Product struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Details   *string  `json:"details"`
	BasePrice *float64 `json:"basePrice"`
	Stock     *int     `json:"stock"`
	Sale      *int     `json:"sale"`
	IDBranch  *int     `json:"id_branch"`
	IDControl *int     `json:"id_control"`
}

type ProductByID struct {
	ID string `json:"id"`
}

type User struct {
	ID               string  `json:"id"`
	Name             *string `json:"name"`
	LastName         *string `json:"lastName"`
	Nickname         string  `json:"nickname"`
	Mail             *string `json:"mail"`
	Phone            *string `json:"phone"`
	Password         string  `json:"password"`
	Admin            *bool   `json:"admin"`
	Root             *bool   `json:"root"`
	Active           *bool   `json:"active"`
	RegistrationDate *string `json:"registrationDate"`
	IDBranch         *int    `json:"id_branch"`
}

type UserByID struct {
	ID string `json:"id"`
}
